name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm i
      - run: pnpm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm i
      - run: pnpm run lint -- --max-warnings 0 && npx prettier --check "**/*.{ts,tsx,md}" --print-width 200 --end-of-line crlf
